#!/usr/bin/env bash
# Auto-generated by launch.sh — do not edit manually
# Remove --dry-run below for live Gemini calls
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$DIR"
echo "=== CONTEXT ENGINE ==="
echo "Working dir: $DIR"
echo "Waiting 5s for ingester..."
sleep 5
python intel/context_engine.py --dry-run
echo ""
echo "=== Context engine exited. Press Enter to close. ==="
read
