#!/usr/bin/env bash
# Auto-generated by launch.sh — do not edit manually
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$DIR"
echo "=== INGESTER ==="
echo "Working dir: $DIR"
echo ""
RUST_LOG=info ./target/release/ingester.exe
echo ""
echo "=== Ingester exited. Press Enter to close. ==="
read
