#!/usr/bin/env bash
# Auto-generated by launch.sh — do not edit manually
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$DIR"
echo "=== TUI ==="
echo "Working dir: $DIR"
echo "Waiting 3s for ingester to populate props.db..."
sleep 3
PYTHONIOENCODING=utf-8 python tui/app.py
echo ""
echo "=== TUI exited. Press Enter to close. ==="
read
